package com.bistu.intimate.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public CommentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCommentIdIsNull() {
			addCriterion("comment_id is null");
			return (Criteria) this;
		}

		public Criteria andCommentIdIsNotNull() {
			addCriterion("comment_id is not null");
			return (Criteria) this;
		}

		public Criteria andCommentIdEqualTo(Integer value) {
			addCriterion("comment_id =", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotEqualTo(Integer value) {
			addCriterion("comment_id <>", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThan(Integer value) {
			addCriterion("comment_id >", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_id >=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThan(Integer value) {
			addCriterion("comment_id <", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThanOrEqualTo(Integer value) {
			addCriterion("comment_id <=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdIn(List<Integer> values) {
			addCriterion("comment_id in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotIn(List<Integer> values) {
			addCriterion("comment_id not in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdBetween(Integer value1, Integer value2) {
			addCriterion("comment_id between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("comment_id not between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdIsNull() {
			addCriterion("major_detail_id is null");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdIsNotNull() {
			addCriterion("major_detail_id is not null");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdEqualTo(Integer value) {
			addCriterion("major_detail_id =", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdNotEqualTo(Integer value) {
			addCriterion("major_detail_id <>", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdGreaterThan(Integer value) {
			addCriterion("major_detail_id >", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("major_detail_id >=", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdLessThan(Integer value) {
			addCriterion("major_detail_id <", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdLessThanOrEqualTo(Integer value) {
			addCriterion("major_detail_id <=", value, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdIn(List<Integer> values) {
			addCriterion("major_detail_id in", values, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdNotIn(List<Integer> values) {
			addCriterion("major_detail_id not in", values, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdBetween(Integer value1, Integer value2) {
			addCriterion("major_detail_id between", value1, value2, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andMajorDetailIdNotBetween(Integer value1, Integer value2) {
			addCriterion("major_detail_id not between", value1, value2, "majorDetailId");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousIsNull() {
			addCriterion("is_anonymous is null");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousIsNotNull() {
			addCriterion("is_anonymous is not null");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousEqualTo(Byte value) {
			addCriterion("is_anonymous =", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousNotEqualTo(Byte value) {
			addCriterion("is_anonymous <>", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousGreaterThan(Byte value) {
			addCriterion("is_anonymous >", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousGreaterThanOrEqualTo(Byte value) {
			addCriterion("is_anonymous >=", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousLessThan(Byte value) {
			addCriterion("is_anonymous <", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousLessThanOrEqualTo(Byte value) {
			addCriterion("is_anonymous <=", value, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousIn(List<Byte> values) {
			addCriterion("is_anonymous in", values, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousNotIn(List<Byte> values) {
			addCriterion("is_anonymous not in", values, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousBetween(Byte value1, Byte value2) {
			addCriterion("is_anonymous between", value1, value2, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andIsAnonymousNotBetween(Byte value1, Byte value2) {
			addCriterion("is_anonymous not between", value1, value2, "isAnonymous");
			return (Criteria) this;
		}

		public Criteria andCommentContentIsNull() {
			addCriterion("comment_content is null");
			return (Criteria) this;
		}

		public Criteria andCommentContentIsNotNull() {
			addCriterion("comment_content is not null");
			return (Criteria) this;
		}

		public Criteria andCommentContentEqualTo(String value) {
			addCriterion("comment_content =", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentNotEqualTo(String value) {
			addCriterion("comment_content <>", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentGreaterThan(String value) {
			addCriterion("comment_content >", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentGreaterThanOrEqualTo(String value) {
			addCriterion("comment_content >=", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentLessThan(String value) {
			addCriterion("comment_content <", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentLessThanOrEqualTo(String value) {
			addCriterion("comment_content <=", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentLike(String value) {
			addCriterion("comment_content like", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentNotLike(String value) {
			addCriterion("comment_content not like", value, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentIn(List<String> values) {
			addCriterion("comment_content in", values, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentNotIn(List<String> values) {
			addCriterion("comment_content not in", values, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentBetween(String value1, String value2) {
			addCriterion("comment_content between", value1, value2, "commentContent");
			return (Criteria) this;
		}

		public Criteria andCommentContentNotBetween(String value1, String value2) {
			addCriterion("comment_content not between", value1, value2, "commentContent");
			return (Criteria) this;
		}

		public Criteria andYnIsNull() {
			addCriterion("yn is null");
			return (Criteria) this;
		}

		public Criteria andYnIsNotNull() {
			addCriterion("yn is not null");
			return (Criteria) this;
		}

		public Criteria andYnEqualTo(Byte value) {
			addCriterion("yn =", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnNotEqualTo(Byte value) {
			addCriterion("yn <>", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnGreaterThan(Byte value) {
			addCriterion("yn >", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnGreaterThanOrEqualTo(Byte value) {
			addCriterion("yn >=", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnLessThan(Byte value) {
			addCriterion("yn <", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnLessThanOrEqualTo(Byte value) {
			addCriterion("yn <=", value, "yn");
			return (Criteria) this;
		}

		public Criteria andYnIn(List<Byte> values) {
			addCriterion("yn in", values, "yn");
			return (Criteria) this;
		}

		public Criteria andYnNotIn(List<Byte> values) {
			addCriterion("yn not in", values, "yn");
			return (Criteria) this;
		}

		public Criteria andYnBetween(Byte value1, Byte value2) {
			addCriterion("yn between", value1, value2, "yn");
			return (Criteria) this;
		}

		public Criteria andYnNotBetween(Byte value1, Byte value2) {
			addCriterion("yn not between", value1, value2, "yn");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated do_not_delete_during_merge Tue May 03 20:51:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}