package com.bistu.intimate.dto;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Integer commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.major_detail_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Integer majorDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.is_anonymous
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Byte isAnonymous;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_content
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private String commentContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.yn
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Byte yn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.create_time
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment_id
	 * @return  the value of comment.comment_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Integer getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment_id
	 * @param commentId  the value for comment.comment_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.user_id
	 * @return  the value of comment.user_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.user_id
	 * @param userId  the value for comment.user_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.major_detail_id
	 * @return  the value of comment.major_detail_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Integer getMajorDetailId() {
		return majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.major_detail_id
	 * @param majorDetailId  the value for comment.major_detail_id
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setMajorDetailId(Integer majorDetailId) {
		this.majorDetailId = majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.is_anonymous
	 * @return  the value of comment.is_anonymous
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Byte getIsAnonymous() {
		return isAnonymous;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.is_anonymous
	 * @param isAnonymous  the value for comment.is_anonymous
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setIsAnonymous(Byte isAnonymous) {
		this.isAnonymous = isAnonymous;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment_content
	 * @return  the value of comment.comment_content
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public String getCommentContent() {
		return commentContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment_content
	 * @param commentContent  the value for comment.comment_content
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.yn
	 * @return  the value of comment.yn
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Byte getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.yn
	 * @param yn  the value for comment.yn
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setYn(Byte yn) {
		this.yn = yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.create_time
	 * @return  the value of comment.create_time
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.create_time
	 * @param createTime  the value for comment.create_time
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}