package com.bistu.intimate.dto;

public class MajorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String majorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_class
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String majorClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String majorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.lesson1_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String lesson1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.lesson2_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String lesson2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.lesson3_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String lesson3Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.lesson4_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String lesson4Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String majorIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_info.major_direction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String majorDirection;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_id
     *
     * @return the value of major_info.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_id
     *
     * @param majorId the value for major_info.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_name
     *
     * @return the value of major_info.major_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_name
     *
     * @param majorName the value for major_info.major_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_class
     *
     * @return the value of major_info.major_class
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getMajorClass() {
        return majorClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_class
     *
     * @param majorClass the value for major_info.major_class
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorClass(String majorClass) {
        this.majorClass = majorClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_type
     *
     * @return the value of major_info.major_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getMajorType() {
        return majorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_type
     *
     * @param majorType the value for major_info.major_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorType(String majorType) {
        this.majorType = majorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.lesson1_name
     *
     * @return the value of major_info.lesson1_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getLesson1Name() {
        return lesson1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.lesson1_name
     *
     * @param lesson1Name the value for major_info.lesson1_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setLesson1Name(String lesson1Name) {
        this.lesson1Name = lesson1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.lesson2_name
     *
     * @return the value of major_info.lesson2_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getLesson2Name() {
        return lesson2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.lesson2_name
     *
     * @param lesson2Name the value for major_info.lesson2_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setLesson2Name(String lesson2Name) {
        this.lesson2Name = lesson2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.lesson3_name
     *
     * @return the value of major_info.lesson3_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getLesson3Name() {
        return lesson3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.lesson3_name
     *
     * @param lesson3Name the value for major_info.lesson3_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setLesson3Name(String lesson3Name) {
        this.lesson3Name = lesson3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.lesson4_name
     *
     * @return the value of major_info.lesson4_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getLesson4Name() {
        return lesson4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.lesson4_name
     *
     * @param lesson4Name the value for major_info.lesson4_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setLesson4Name(String lesson4Name) {
        this.lesson4Name = lesson4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_introduction
     *
     * @return the value of major_info.major_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getMajorIntroduction() {
        return majorIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_introduction
     *
     * @param majorIntroduction the value for major_info.major_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorIntroduction(String majorIntroduction) {
        this.majorIntroduction = majorIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_info.major_direction
     *
     * @return the value of major_info.major_direction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getMajorDirection() {
        return majorDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_info.major_direction
     *
     * @param majorDirection the value for major_info.major_direction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorDirection(String majorDirection) {
        this.majorDirection = majorDirection;
    }
}