package com.bistu.intimate.dto;

import java.util.Date;

public class MajorDetailPassingScore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.passing_score_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer passingScoreId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.major_detial_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer majorDetialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.year
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.total_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer totalPassingScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.lesson1_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer lesson1PassingScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.lesson2_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer lesson2PassingScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.lesson3_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer lesson3PassingScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.lesson4_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer lesson4PassingScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Byte yn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail_passing_score.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.passing_score_id
	 * @return  the value of major_detail_passing_score.passing_score_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getPassingScoreId() {
		return passingScoreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.passing_score_id
	 * @param passingScoreId  the value for major_detail_passing_score.passing_score_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setPassingScoreId(Integer passingScoreId) {
		this.passingScoreId = passingScoreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.major_detial_id
	 * @return  the value of major_detail_passing_score.major_detial_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getMajorDetialId() {
		return majorDetialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.major_detial_id
	 * @param majorDetialId  the value for major_detail_passing_score.major_detial_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setMajorDetialId(Integer majorDetialId) {
		this.majorDetialId = majorDetialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.year
	 * @return  the value of major_detail_passing_score.year
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.year
	 * @param year  the value for major_detail_passing_score.year
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.total_passing_score
	 * @return  the value of major_detail_passing_score.total_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getTotalPassingScore() {
		return totalPassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.total_passing_score
	 * @param totalPassingScore  the value for major_detail_passing_score.total_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setTotalPassingScore(Integer totalPassingScore) {
		this.totalPassingScore = totalPassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.lesson1_passing_score
	 * @return  the value of major_detail_passing_score.lesson1_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getLesson1PassingScore() {
		return lesson1PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.lesson1_passing_score
	 * @param lesson1PassingScore  the value for major_detail_passing_score.lesson1_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setLesson1PassingScore(Integer lesson1PassingScore) {
		this.lesson1PassingScore = lesson1PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.lesson2_passing_score
	 * @return  the value of major_detail_passing_score.lesson2_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getLesson2PassingScore() {
		return lesson2PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.lesson2_passing_score
	 * @param lesson2PassingScore  the value for major_detail_passing_score.lesson2_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setLesson2PassingScore(Integer lesson2PassingScore) {
		this.lesson2PassingScore = lesson2PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.lesson3_passing_score
	 * @return  the value of major_detail_passing_score.lesson3_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getLesson3PassingScore() {
		return lesson3PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.lesson3_passing_score
	 * @param lesson3PassingScore  the value for major_detail_passing_score.lesson3_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setLesson3PassingScore(Integer lesson3PassingScore) {
		this.lesson3PassingScore = lesson3PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.lesson4_passing_score
	 * @return  the value of major_detail_passing_score.lesson4_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getLesson4PassingScore() {
		return lesson4PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.lesson4_passing_score
	 * @param lesson4PassingScore  the value for major_detail_passing_score.lesson4_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setLesson4PassingScore(Integer lesson4PassingScore) {
		this.lesson4PassingScore = lesson4PassingScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.yn
	 * @return  the value of major_detail_passing_score.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Byte getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.yn
	 * @param yn  the value for major_detail_passing_score.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setYn(Byte yn) {
		this.yn = yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.create_time
	 * @return  the value of major_detail_passing_score.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.create_time
	 * @param createTime  the value for major_detail_passing_score.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail_passing_score.update_time
	 * @return  the value of major_detail_passing_score.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail_passing_score.update_time
	 * @param updateTime  the value for major_detail_passing_score.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}