package com.bistu.intimate.dto;

import java.util.ArrayList;
import java.util.List;

public class MajorInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public MajorInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMajorIdIsNull() {
            addCriterion("major_id is null");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNotNull() {
            addCriterion("major_id is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIdEqualTo(Integer value) {
            addCriterion("major_id =", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotEqualTo(Integer value) {
            addCriterion("major_id <>", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThan(Integer value) {
            addCriterion("major_id >", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("major_id >=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThan(Integer value) {
            addCriterion("major_id <", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThanOrEqualTo(Integer value) {
            addCriterion("major_id <=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIn(List<Integer> values) {
            addCriterion("major_id in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotIn(List<Integer> values) {
            addCriterion("major_id not in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdBetween(Integer value1, Integer value2) {
            addCriterion("major_id between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("major_id not between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorNameIsNull() {
            addCriterion("major_name is null");
            return (Criteria) this;
        }

        public Criteria andMajorNameIsNotNull() {
            addCriterion("major_name is not null");
            return (Criteria) this;
        }

        public Criteria andMajorNameEqualTo(String value) {
            addCriterion("major_name =", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameNotEqualTo(String value) {
            addCriterion("major_name <>", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameGreaterThan(String value) {
            addCriterion("major_name >", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameGreaterThanOrEqualTo(String value) {
            addCriterion("major_name >=", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameLessThan(String value) {
            addCriterion("major_name <", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameLessThanOrEqualTo(String value) {
            addCriterion("major_name <=", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameLike(String value) {
            addCriterion("major_name like", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameNotLike(String value) {
            addCriterion("major_name not like", value, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameIn(List<String> values) {
            addCriterion("major_name in", values, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameNotIn(List<String> values) {
            addCriterion("major_name not in", values, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameBetween(String value1, String value2) {
            addCriterion("major_name between", value1, value2, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorNameNotBetween(String value1, String value2) {
            addCriterion("major_name not between", value1, value2, "majorName");
            return (Criteria) this;
        }

        public Criteria andMajorClassIsNull() {
            addCriterion("major_class is null");
            return (Criteria) this;
        }

        public Criteria andMajorClassIsNotNull() {
            addCriterion("major_class is not null");
            return (Criteria) this;
        }

        public Criteria andMajorClassEqualTo(String value) {
            addCriterion("major_class =", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassNotEqualTo(String value) {
            addCriterion("major_class <>", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassGreaterThan(String value) {
            addCriterion("major_class >", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassGreaterThanOrEqualTo(String value) {
            addCriterion("major_class >=", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassLessThan(String value) {
            addCriterion("major_class <", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassLessThanOrEqualTo(String value) {
            addCriterion("major_class <=", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassLike(String value) {
            addCriterion("major_class like", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassNotLike(String value) {
            addCriterion("major_class not like", value, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassIn(List<String> values) {
            addCriterion("major_class in", values, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassNotIn(List<String> values) {
            addCriterion("major_class not in", values, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassBetween(String value1, String value2) {
            addCriterion("major_class between", value1, value2, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorClassNotBetween(String value1, String value2) {
            addCriterion("major_class not between", value1, value2, "majorClass");
            return (Criteria) this;
        }

        public Criteria andMajorTypeIsNull() {
            addCriterion("major_type is null");
            return (Criteria) this;
        }

        public Criteria andMajorTypeIsNotNull() {
            addCriterion("major_type is not null");
            return (Criteria) this;
        }

        public Criteria andMajorTypeEqualTo(String value) {
            addCriterion("major_type =", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeNotEqualTo(String value) {
            addCriterion("major_type <>", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeGreaterThan(String value) {
            addCriterion("major_type >", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("major_type >=", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeLessThan(String value) {
            addCriterion("major_type <", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeLessThanOrEqualTo(String value) {
            addCriterion("major_type <=", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeLike(String value) {
            addCriterion("major_type like", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeNotLike(String value) {
            addCriterion("major_type not like", value, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeIn(List<String> values) {
            addCriterion("major_type in", values, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeNotIn(List<String> values) {
            addCriterion("major_type not in", values, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeBetween(String value1, String value2) {
            addCriterion("major_type between", value1, value2, "majorType");
            return (Criteria) this;
        }

        public Criteria andMajorTypeNotBetween(String value1, String value2) {
            addCriterion("major_type not between", value1, value2, "majorType");
            return (Criteria) this;
        }

        public Criteria andLesson1NameIsNull() {
            addCriterion("lesson1_name is null");
            return (Criteria) this;
        }

        public Criteria andLesson1NameIsNotNull() {
            addCriterion("lesson1_name is not null");
            return (Criteria) this;
        }

        public Criteria andLesson1NameEqualTo(String value) {
            addCriterion("lesson1_name =", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameNotEqualTo(String value) {
            addCriterion("lesson1_name <>", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameGreaterThan(String value) {
            addCriterion("lesson1_name >", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameGreaterThanOrEqualTo(String value) {
            addCriterion("lesson1_name >=", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameLessThan(String value) {
            addCriterion("lesson1_name <", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameLessThanOrEqualTo(String value) {
            addCriterion("lesson1_name <=", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameLike(String value) {
            addCriterion("lesson1_name like", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameNotLike(String value) {
            addCriterion("lesson1_name not like", value, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameIn(List<String> values) {
            addCriterion("lesson1_name in", values, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameNotIn(List<String> values) {
            addCriterion("lesson1_name not in", values, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameBetween(String value1, String value2) {
            addCriterion("lesson1_name between", value1, value2, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson1NameNotBetween(String value1, String value2) {
            addCriterion("lesson1_name not between", value1, value2, "lesson1Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameIsNull() {
            addCriterion("lesson2_name is null");
            return (Criteria) this;
        }

        public Criteria andLesson2NameIsNotNull() {
            addCriterion("lesson2_name is not null");
            return (Criteria) this;
        }

        public Criteria andLesson2NameEqualTo(String value) {
            addCriterion("lesson2_name =", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameNotEqualTo(String value) {
            addCriterion("lesson2_name <>", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameGreaterThan(String value) {
            addCriterion("lesson2_name >", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameGreaterThanOrEqualTo(String value) {
            addCriterion("lesson2_name >=", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameLessThan(String value) {
            addCriterion("lesson2_name <", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameLessThanOrEqualTo(String value) {
            addCriterion("lesson2_name <=", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameLike(String value) {
            addCriterion("lesson2_name like", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameNotLike(String value) {
            addCriterion("lesson2_name not like", value, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameIn(List<String> values) {
            addCriterion("lesson2_name in", values, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameNotIn(List<String> values) {
            addCriterion("lesson2_name not in", values, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameBetween(String value1, String value2) {
            addCriterion("lesson2_name between", value1, value2, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson2NameNotBetween(String value1, String value2) {
            addCriterion("lesson2_name not between", value1, value2, "lesson2Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameIsNull() {
            addCriterion("lesson3_name is null");
            return (Criteria) this;
        }

        public Criteria andLesson3NameIsNotNull() {
            addCriterion("lesson3_name is not null");
            return (Criteria) this;
        }

        public Criteria andLesson3NameEqualTo(String value) {
            addCriterion("lesson3_name =", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameNotEqualTo(String value) {
            addCriterion("lesson3_name <>", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameGreaterThan(String value) {
            addCriterion("lesson3_name >", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameGreaterThanOrEqualTo(String value) {
            addCriterion("lesson3_name >=", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameLessThan(String value) {
            addCriterion("lesson3_name <", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameLessThanOrEqualTo(String value) {
            addCriterion("lesson3_name <=", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameLike(String value) {
            addCriterion("lesson3_name like", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameNotLike(String value) {
            addCriterion("lesson3_name not like", value, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameIn(List<String> values) {
            addCriterion("lesson3_name in", values, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameNotIn(List<String> values) {
            addCriterion("lesson3_name not in", values, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameBetween(String value1, String value2) {
            addCriterion("lesson3_name between", value1, value2, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson3NameNotBetween(String value1, String value2) {
            addCriterion("lesson3_name not between", value1, value2, "lesson3Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameIsNull() {
            addCriterion("lesson4_name is null");
            return (Criteria) this;
        }

        public Criteria andLesson4NameIsNotNull() {
            addCriterion("lesson4_name is not null");
            return (Criteria) this;
        }

        public Criteria andLesson4NameEqualTo(String value) {
            addCriterion("lesson4_name =", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameNotEqualTo(String value) {
            addCriterion("lesson4_name <>", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameGreaterThan(String value) {
            addCriterion("lesson4_name >", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameGreaterThanOrEqualTo(String value) {
            addCriterion("lesson4_name >=", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameLessThan(String value) {
            addCriterion("lesson4_name <", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameLessThanOrEqualTo(String value) {
            addCriterion("lesson4_name <=", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameLike(String value) {
            addCriterion("lesson4_name like", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameNotLike(String value) {
            addCriterion("lesson4_name not like", value, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameIn(List<String> values) {
            addCriterion("lesson4_name in", values, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameNotIn(List<String> values) {
            addCriterion("lesson4_name not in", values, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameBetween(String value1, String value2) {
            addCriterion("lesson4_name between", value1, value2, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andLesson4NameNotBetween(String value1, String value2) {
            addCriterion("lesson4_name not between", value1, value2, "lesson4Name");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionIsNull() {
            addCriterion("major_introduction is null");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionIsNotNull() {
            addCriterion("major_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionEqualTo(String value) {
            addCriterion("major_introduction =", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionNotEqualTo(String value) {
            addCriterion("major_introduction <>", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionGreaterThan(String value) {
            addCriterion("major_introduction >", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("major_introduction >=", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionLessThan(String value) {
            addCriterion("major_introduction <", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionLessThanOrEqualTo(String value) {
            addCriterion("major_introduction <=", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionLike(String value) {
            addCriterion("major_introduction like", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionNotLike(String value) {
            addCriterion("major_introduction not like", value, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionIn(List<String> values) {
            addCriterion("major_introduction in", values, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionNotIn(List<String> values) {
            addCriterion("major_introduction not in", values, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionBetween(String value1, String value2) {
            addCriterion("major_introduction between", value1, value2, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorIntroductionNotBetween(String value1, String value2) {
            addCriterion("major_introduction not between", value1, value2, "majorIntroduction");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionIsNull() {
            addCriterion("major_direction is null");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionIsNotNull() {
            addCriterion("major_direction is not null");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionEqualTo(String value) {
            addCriterion("major_direction =", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionNotEqualTo(String value) {
            addCriterion("major_direction <>", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionGreaterThan(String value) {
            addCriterion("major_direction >", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("major_direction >=", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionLessThan(String value) {
            addCriterion("major_direction <", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionLessThanOrEqualTo(String value) {
            addCriterion("major_direction <=", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionLike(String value) {
            addCriterion("major_direction like", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionNotLike(String value) {
            addCriterion("major_direction not like", value, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionIn(List<String> values) {
            addCriterion("major_direction in", values, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionNotIn(List<String> values) {
            addCriterion("major_direction not in", values, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionBetween(String value1, String value2) {
            addCriterion("major_direction between", value1, value2, "majorDirection");
            return (Criteria) this;
        }

        public Criteria andMajorDirectionNotBetween(String value1, String value2) {
            addCriterion("major_direction not between", value1, value2, "majorDirection");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table major_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 07 21:54:18 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}