package com.bistu.intimate.dto;

public class MajorDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer majorDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.enrollment_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer enrollmentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.participant_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer participantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.offer_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer offerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_detail.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Byte yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.major_detail_id
     *
     * @return the value of major_detail.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getMajorDetailId() {
        return majorDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.major_detail_id
     *
     * @param majorDetailId the value for major_detail.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorDetailId(Integer majorDetailId) {
        this.majorDetailId = majorDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.school_id
     *
     * @return the value of major_detail.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.school_id
     *
     * @param schoolId the value for major_detail.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.major_id
     *
     * @return the value of major_detail.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.major_id
     *
     * @param majorId the value for major_detail.major_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.enrollment_no
     *
     * @return the value of major_detail.enrollment_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getEnrollmentNo() {
        return enrollmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.enrollment_no
     *
     * @param enrollmentNo the value for major_detail.enrollment_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setEnrollmentNo(Integer enrollmentNo) {
        this.enrollmentNo = enrollmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.participant_no
     *
     * @return the value of major_detail.participant_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getParticipantNo() {
        return participantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.participant_no
     *
     * @param participantNo the value for major_detail.participant_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setParticipantNo(Integer participantNo) {
        this.participantNo = participantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.offer_no
     *
     * @return the value of major_detail.offer_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getOfferNo() {
        return offerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.offer_no
     *
     * @param offerNo the value for major_detail.offer_no
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setOfferNo(Integer offerNo) {
        this.offerNo = offerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_detail.yn
     *
     * @return the value of major_detail.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_detail.yn
     *
     * @param yn the value for major_detail.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }
}