package com.bistu.intimate.dto;

import java.util.Date;

public class MajorDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.major_detail_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer majorDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.school_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer schoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.major_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer majorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.enrollment_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer enrollmentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.participant_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer participantNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.offer_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Integer offerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.lesson1_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private String lesson1Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.lesson2_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private String lesson2Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.lesson3_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private String lesson3Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.lesson4_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private String lesson4Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.yn
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Byte yn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.create_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major_detail.update_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.major_detail_id
	 * @return  the value of major_detail.major_detail_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getMajorDetailId() {
		return majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.major_detail_id
	 * @param majorDetailId  the value for major_detail.major_detail_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setMajorDetailId(Integer majorDetailId) {
		this.majorDetailId = majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.school_id
	 * @return  the value of major_detail.school_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getSchoolId() {
		return schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.school_id
	 * @param schoolId  the value for major_detail.school_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.major_id
	 * @return  the value of major_detail.major_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getMajorId() {
		return majorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.major_id
	 * @param majorId  the value for major_detail.major_id
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.enrollment_no
	 * @return  the value of major_detail.enrollment_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getEnrollmentNo() {
		return enrollmentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.enrollment_no
	 * @param enrollmentNo  the value for major_detail.enrollment_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setEnrollmentNo(Integer enrollmentNo) {
		this.enrollmentNo = enrollmentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.participant_no
	 * @return  the value of major_detail.participant_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getParticipantNo() {
		return participantNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.participant_no
	 * @param participantNo  the value for major_detail.participant_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setParticipantNo(Integer participantNo) {
		this.participantNo = participantNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.offer_no
	 * @return  the value of major_detail.offer_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Integer getOfferNo() {
		return offerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.offer_no
	 * @param offerNo  the value for major_detail.offer_no
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setOfferNo(Integer offerNo) {
		this.offerNo = offerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.lesson1_name
	 * @return  the value of major_detail.lesson1_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public String getLesson1Name() {
		return lesson1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.lesson1_name
	 * @param lesson1Name  the value for major_detail.lesson1_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setLesson1Name(String lesson1Name) {
		this.lesson1Name = lesson1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.lesson2_name
	 * @return  the value of major_detail.lesson2_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public String getLesson2Name() {
		return lesson2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.lesson2_name
	 * @param lesson2Name  the value for major_detail.lesson2_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setLesson2Name(String lesson2Name) {
		this.lesson2Name = lesson2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.lesson3_name
	 * @return  the value of major_detail.lesson3_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public String getLesson3Name() {
		return lesson3Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.lesson3_name
	 * @param lesson3Name  the value for major_detail.lesson3_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setLesson3Name(String lesson3Name) {
		this.lesson3Name = lesson3Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.lesson4_name
	 * @return  the value of major_detail.lesson4_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public String getLesson4Name() {
		return lesson4Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.lesson4_name
	 * @param lesson4Name  the value for major_detail.lesson4_name
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setLesson4Name(String lesson4Name) {
		this.lesson4Name = lesson4Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.yn
	 * @return  the value of major_detail.yn
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Byte getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.yn
	 * @param yn  the value for major_detail.yn
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setYn(Byte yn) {
		this.yn = yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.create_time
	 * @return  the value of major_detail.create_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.create_time
	 * @param createTime  the value for major_detail.create_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major_detail.update_time
	 * @return  the value of major_detail.update_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major_detail.update_time
	 * @param updateTime  the value for major_detail.update_time
	 * @mbggenerated  Sun Apr 24 21:53:36 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}