package com.bistu.intimate.dto;

public class SchoolInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.province
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.area
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_property
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_character
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolCharacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_rank
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer schoolRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_tel
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_info.school_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private String schoolIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_id
     *
     * @return the value of school_info.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_id
     *
     * @param schoolId the value for school_info.school_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_name
     *
     * @return the value of school_info.school_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_name
     *
     * @param schoolName the value for school_info.school_name
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.province
     *
     * @return the value of school_info.province
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.province
     *
     * @param province the value for school_info.province
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.area
     *
     * @return the value of school_info.area
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.area
     *
     * @param area the value for school_info.area
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_property
     *
     * @return the value of school_info.school_property
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolProperty() {
        return schoolProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_property
     *
     * @param schoolProperty the value for school_info.school_property
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolProperty(String schoolProperty) {
        this.schoolProperty = schoolProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_type
     *
     * @return the value of school_info.school_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolType() {
        return schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_type
     *
     * @param schoolType the value for school_info.school_type
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolType(String schoolType) {
        this.schoolType = schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_character
     *
     * @return the value of school_info.school_character
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolCharacter() {
        return schoolCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_character
     *
     * @param schoolCharacter the value for school_info.school_character
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolCharacter(String schoolCharacter) {
        this.schoolCharacter = schoolCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_rank
     *
     * @return the value of school_info.school_rank
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getSchoolRank() {
        return schoolRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_rank
     *
     * @param schoolRank the value for school_info.school_rank
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolRank(Integer schoolRank) {
        this.schoolRank = schoolRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_tel
     *
     * @return the value of school_info.school_tel
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolTel() {
        return schoolTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_tel
     *
     * @param schoolTel the value for school_info.school_tel
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolTel(String schoolTel) {
        this.schoolTel = schoolTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_info.school_introduction
     *
     * @return the value of school_info.school_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getSchoolIntroduction() {
        return schoolIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_info.school_introduction
     *
     * @param schoolIntroduction the value for school_info.school_introduction
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setSchoolIntroduction(String schoolIntroduction) {
        this.schoolIntroduction = schoolIntroduction;
    }
}