package com.bistu.intimate.dto;

import java.util.ArrayList;
import java.util.List;

public class SchoolInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public SchoolInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(Integer value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(Integer value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(Integer value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(Integer value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(Integer value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<Integer> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<Integer> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(Integer value1, Integer value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyIsNull() {
            addCriterion("school_property is null");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyIsNotNull() {
            addCriterion("school_property is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyEqualTo(String value) {
            addCriterion("school_property =", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyNotEqualTo(String value) {
            addCriterion("school_property <>", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyGreaterThan(String value) {
            addCriterion("school_property >", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("school_property >=", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyLessThan(String value) {
            addCriterion("school_property <", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyLessThanOrEqualTo(String value) {
            addCriterion("school_property <=", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyLike(String value) {
            addCriterion("school_property like", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyNotLike(String value) {
            addCriterion("school_property not like", value, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyIn(List<String> values) {
            addCriterion("school_property in", values, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyNotIn(List<String> values) {
            addCriterion("school_property not in", values, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyBetween(String value1, String value2) {
            addCriterion("school_property between", value1, value2, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolPropertyNotBetween(String value1, String value2) {
            addCriterion("school_property not between", value1, value2, "schoolProperty");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNull() {
            addCriterion("school_type is null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNotNull() {
            addCriterion("school_type is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeEqualTo(String value) {
            addCriterion("school_type =", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotEqualTo(String value) {
            addCriterion("school_type <>", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThan(String value) {
            addCriterion("school_type >", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThanOrEqualTo(String value) {
            addCriterion("school_type >=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThan(String value) {
            addCriterion("school_type <", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThanOrEqualTo(String value) {
            addCriterion("school_type <=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLike(String value) {
            addCriterion("school_type like", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotLike(String value) {
            addCriterion("school_type not like", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIn(List<String> values) {
            addCriterion("school_type in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotIn(List<String> values) {
            addCriterion("school_type not in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeBetween(String value1, String value2) {
            addCriterion("school_type between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotBetween(String value1, String value2) {
            addCriterion("school_type not between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterIsNull() {
            addCriterion("school_character is null");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterIsNotNull() {
            addCriterion("school_character is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterEqualTo(String value) {
            addCriterion("school_character =", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterNotEqualTo(String value) {
            addCriterion("school_character <>", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterGreaterThan(String value) {
            addCriterion("school_character >", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterGreaterThanOrEqualTo(String value) {
            addCriterion("school_character >=", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterLessThan(String value) {
            addCriterion("school_character <", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterLessThanOrEqualTo(String value) {
            addCriterion("school_character <=", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterLike(String value) {
            addCriterion("school_character like", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterNotLike(String value) {
            addCriterion("school_character not like", value, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterIn(List<String> values) {
            addCriterion("school_character in", values, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterNotIn(List<String> values) {
            addCriterion("school_character not in", values, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterBetween(String value1, String value2) {
            addCriterion("school_character between", value1, value2, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolCharacterNotBetween(String value1, String value2) {
            addCriterion("school_character not between", value1, value2, "schoolCharacter");
            return (Criteria) this;
        }

        public Criteria andSchoolRankIsNull() {
            addCriterion("school_rank is null");
            return (Criteria) this;
        }

        public Criteria andSchoolRankIsNotNull() {
            addCriterion("school_rank is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolRankEqualTo(Integer value) {
            addCriterion("school_rank =", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankNotEqualTo(Integer value) {
            addCriterion("school_rank <>", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankGreaterThan(Integer value) {
            addCriterion("school_rank >", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_rank >=", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankLessThan(Integer value) {
            addCriterion("school_rank <", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankLessThanOrEqualTo(Integer value) {
            addCriterion("school_rank <=", value, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankIn(List<Integer> values) {
            addCriterion("school_rank in", values, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankNotIn(List<Integer> values) {
            addCriterion("school_rank not in", values, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankBetween(Integer value1, Integer value2) {
            addCriterion("school_rank between", value1, value2, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolRankNotBetween(Integer value1, Integer value2) {
            addCriterion("school_rank not between", value1, value2, "schoolRank");
            return (Criteria) this;
        }

        public Criteria andSchoolTelIsNull() {
            addCriterion("school_tel is null");
            return (Criteria) this;
        }

        public Criteria andSchoolTelIsNotNull() {
            addCriterion("school_tel is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolTelEqualTo(String value) {
            addCriterion("school_tel =", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelNotEqualTo(String value) {
            addCriterion("school_tel <>", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelGreaterThan(String value) {
            addCriterion("school_tel >", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelGreaterThanOrEqualTo(String value) {
            addCriterion("school_tel >=", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelLessThan(String value) {
            addCriterion("school_tel <", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelLessThanOrEqualTo(String value) {
            addCriterion("school_tel <=", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelLike(String value) {
            addCriterion("school_tel like", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelNotLike(String value) {
            addCriterion("school_tel not like", value, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelIn(List<String> values) {
            addCriterion("school_tel in", values, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelNotIn(List<String> values) {
            addCriterion("school_tel not in", values, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelBetween(String value1, String value2) {
            addCriterion("school_tel between", value1, value2, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolTelNotBetween(String value1, String value2) {
            addCriterion("school_tel not between", value1, value2, "schoolTel");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionIsNull() {
            addCriterion("school_introduction is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionIsNotNull() {
            addCriterion("school_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionEqualTo(String value) {
            addCriterion("school_introduction =", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionNotEqualTo(String value) {
            addCriterion("school_introduction <>", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionGreaterThan(String value) {
            addCriterion("school_introduction >", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("school_introduction >=", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionLessThan(String value) {
            addCriterion("school_introduction <", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionLessThanOrEqualTo(String value) {
            addCriterion("school_introduction <=", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionLike(String value) {
            addCriterion("school_introduction like", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionNotLike(String value) {
            addCriterion("school_introduction not like", value, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionIn(List<String> values) {
            addCriterion("school_introduction in", values, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionNotIn(List<String> values) {
            addCriterion("school_introduction not in", values, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionBetween(String value1, String value2) {
            addCriterion("school_introduction between", value1, value2, "schoolIntroduction");
            return (Criteria) this;
        }

        public Criteria andSchoolIntroductionNotBetween(String value1, String value2) {
            addCriterion("school_introduction not between", value1, value2, "schoolIntroduction");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 07 21:54:18 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}