package com.bistu.intimate.dto;

import java.util.Date;

public class UserCollection {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.collection_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer collectionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.major_detail_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer majorDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Byte yn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_collection.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.collection_id
	 * @return  the value of user_collection.collection_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getCollectionId() {
		return collectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.collection_id
	 * @param collectionId  the value for user_collection.collection_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.user_id
	 * @return  the value of user_collection.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.user_id
	 * @param userId  the value for user_collection.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.major_detail_id
	 * @return  the value of user_collection.major_detail_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getMajorDetailId() {
		return majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.major_detail_id
	 * @param majorDetailId  the value for user_collection.major_detail_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setMajorDetailId(Integer majorDetailId) {
		this.majorDetailId = majorDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.yn
	 * @return  the value of user_collection.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Byte getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.yn
	 * @param yn  the value for user_collection.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setYn(Byte yn) {
		this.yn = yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.create_time
	 * @return  the value of user_collection.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.create_time
	 * @param createTime  the value for user_collection.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_collection.update_time
	 * @return  the value of user_collection.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_collection.update_time
	 * @param updateTime  the value for user_collection.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}