package com.bistu.intimate.dto;

public class UserCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.collection_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.user_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Integer majorDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    private Byte yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.collection_id
     *
     * @return the value of user_collection.collection_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.collection_id
     *
     * @param collectionId the value for user_collection.collection_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.user_id
     *
     * @return the value of user_collection.user_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.user_id
     *
     * @param userId the value for user_collection.user_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.major_detail_id
     *
     * @return the value of user_collection.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Integer getMajorDetailId() {
        return majorDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.major_detail_id
     *
     * @param majorDetailId the value for user_collection.major_detail_id
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setMajorDetailId(Integer majorDetailId) {
        this.majorDetailId = majorDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.yn
     *
     * @return the value of user_collection.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.yn
     *
     * @param yn the value for user_collection.yn
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }
}