package com.bistu.intimate.dto;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.real_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.school
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.is_manager
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Byte isManager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	private Byte yn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.real_name
	 * @return  the value of user.real_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.real_name
	 * @param realName  the value for user.real_name
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.school
	 * @return  the value of user.school
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.school
	 * @param school  the value for user.school
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.is_manager
	 * @return  the value of user.is_manager
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Byte getIsManager() {
		return isManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.is_manager
	 * @param isManager  the value for user.is_manager
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setIsManager(Byte isManager) {
		this.isManager = isManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_time
	 * @return  the value of user.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_time
	 * @param updateTime  the value for user.update_time
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.yn
	 * @return  the value of user.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public Byte getYn() {
		return yn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.yn
	 * @param yn  the value for user.yn
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	public void setYn(Byte yn) {
		this.yn = yn;
	}
}