package com.bistu.intimate.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bistu.intimate.dto.Comment;
import com.bistu.intimate.dto.CommentExample;
import com.bistu.intimate.vo.CommentVo;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int deleteByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	Comment selectByPrimaryKey(Integer commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Tue May 03 20:52:18 CST 2016
	 */
	int updateByPrimaryKey(Comment record);
	
	/**
	 * 根据majorDetailId查询Vo
	 * @param majorDetailId
	 * @return
	 */
	List<CommentVo> queryCommentsByMajorDetailId(Integer majorDetailId);
}