package com.bistu.intimate.dao;

import com.bistu.intimate.dto.MajorInfo;
import com.bistu.intimate.dto.MajorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int countByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int deleteByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int deleteByPrimaryKey(Integer majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int insert(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int insertSelective(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    List<MajorInfo> selectByExample(MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    MajorInfo selectByPrimaryKey(Integer majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") MajorInfo record, @Param("example") MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int updateByExample(@Param("record") MajorInfo record, @Param("example") MajorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int updateByPrimaryKeySelective(MajorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_info
     *
     * @mbggenerated Thu Apr 07 21:54:18 CST 2016
     */
    int updateByPrimaryKey(MajorInfo record);
}