package com.bistu.intimate.dao;

import com.bistu.intimate.dto.MajorDetailPassingScore;
import com.bistu.intimate.dto.MajorDetailPassingScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorDetailPassingScoreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int countByExample(MajorDetailPassingScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int deleteByExample(MajorDetailPassingScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer passingScoreId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int insert(MajorDetailPassingScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int insertSelective(MajorDetailPassingScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	List<MajorDetailPassingScore> selectByExample(MajorDetailPassingScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	MajorDetailPassingScore selectByPrimaryKey(Integer passingScoreId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") MajorDetailPassingScore record,
			@Param("example") MajorDetailPassingScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int updateByExample(@Param("record") MajorDetailPassingScore record,
			@Param("example") MajorDetailPassingScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int updateByPrimaryKeySelective(MajorDetailPassingScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major_detail_passing_score
	 * @mbggenerated  Tue Apr 12 22:32:36 CST 2016
	 */
	int updateByPrimaryKey(MajorDetailPassingScore record);
	
}